name: eye_tracking_plus
description: Flutter eye tracking (Web/iOS/Android) with sub-degree accuracy and Web-only attention-aware confidence.
version: 0.1.2
homepage: https://pub.dev/packages/eye_tracking_plus
repository: https://github.com/aydiaj/eye_tracking_plus
issue_tracker: https://github.com/aydiaj/eye_tracking_plus/issues

# Link to the original project/docs for attribution:
documentation: https://github.com/Piyushhhhh/eye_tracking

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - eye-tracking
  - computer-vision
  - gaze-tracking
  - proctoring
  - anti-cheating

flutter:
  plugin:
    platforms:
      web:
        pluginClass: EyeTrackingWeb
        fileName: eye_tracking_web.dart
      android:
        package: dev.eyetracking.flutter
        pluginClass: EyeTrackingPlugin
      ios:
        pluginClass: EyeTrackingPlugin


